baseURL = "https://1697-20747.github.io/"
languageCode = "en-gb"
title = "[1697, 20747]"
theme = "PaperMod"
paginate = 10

[minify]
  disableCSS = true

[params]
  author = "Your Name"
  description = "Writing on Economics, Data Analytics, Computer Science & more."
  defaultTheme = "dark"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButtonInSectionTermList = false
  UseHugoToc = true
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false
  math = true

[params.homeInfoParams]
  Title = "Hi, I'm [1697, 20747]* 👋"
  Content = """
This is my personal webpage where I write (dump random thoughts?) about Economics, Data Analytics, Credit Risk, Computer Science, and whatever else catches my attention within my domains of interest (minimal expertise).<br><br>
I work with data across finance and comp science, and the usual open source systems. These are essentially my notes made public. Whilst the day job is finance, all my comp science is for the most part in my own time. I like my freedom. 
Source material is all public domain, or my own work, with or without data analytics added on top. See references if you want to check it.
Some of the chunkier posts are quite technical and take me longer, so I often iterate through them, updating periodically. Errors are all mine! 
Most of the data analytics and charts are all python bash files set to run outside of any IDE. Some of the projects are a mix of languages. It is all open source now.<br><br>
I hope the message is clear despite the informal phrasing, the text is not AI generated, although I am using it now more on markdown for tables from csv files. Also for methods in programming. I am a pretty average programmer, my chosen domain of frustration is low level programming on small devices, for which I need to know quite a bit of machine learning.<br><br>
You won't find me on social media, ever. This is it really, unless you are on one of my very few WhatsApp groups.
<hr>
<small>*token tokenizer joke, if that is your thing. If it's not, you are possibly in the wrong place....</small>
"""


  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/1697-20747"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/bruce-schultz-19020039"
  [[params.socialIcons]]
    name = "rss"
    url = "/index.xml"
  [params.profileMode]
    enabled = true
    imageUrl = "/images/avatar.png"
    imageWidth = 140
    imageHeight = 140
  [params.assets]
    favicon = "/images/favicon.ico"
    disableHLJS = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = false
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    lineNumbersInTable = true
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    identifier = "blog/economics"
    name = "Economics"
    url = "/blog/economics/"
    weight = 10
  [[menu.main]]
    identifier = "blog/data-analytics"
    name = "Data Analytics"
    url = "/blog/data-analytics/"
    weight = 20
  [[menu.main]]
    identifier = "blog/comp-science"
    name = "Comp Science"
    url = "/blog/comp-science/"
    weight = 30
  [[menu.main]]
    identifier = "blog/credit-risk"
    name = "Credit Risk"
    url = "/blog/credit-risk/"
    weight = 40
  [[menu.main]]
    identifier = "blog/other"
    name = "Other"
    url = "/blog/other/"
    weight = 50
  [[menu.main]]
    identifier = "blog/philosophy"
    name = "Philosophy"
    url = "/blog/philosophy/"
    weight = 60
  [[menu.main]]
    identifier = "blog/bjj"
    name = "BJJ"
    url = "/blog/bjj/"
    weight = 70
  [[menu.main]]
    identifier = "blog/unhelpful-advice"
    name = "Unhelpful Advice"
    url = "/blog/unhelpful-advice/"
    weight = 80
  [[menu.main]]
    identifier = "blog/books"
    name = "Books"
    url = "/blog/books/"
    weight = 90
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 100
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 95
